package org.example.entitis;

import jakarta.persistence.*;

@Entity
@Table(name = "clients")
public class Cliente {

    // ES: Identificador único del cliente. Se genera automáticamente con autoincremento.
    // EN: Unique identifier of the client. Automatically generated using auto-increment.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    // ES: Nombre del cliente. Campo obligatorio (NOT NULL), longitud máxima de 50 caracteres.
    // EN: Client's first name. Required field (NOT NULL), max length 50 characters.
    @Column(nullable = false, length = 50)
    private String nombre;

    // ES: Apellidos del cliente. Campo obligatorio (NOT NULL), longitud máxima de 50 caracteres.
    // EN: Client's last name. Required field (NOT NULL), max length 50 characters.
    @Column(nullable = false, length = 50)
    private String apellidos;

    // ES: Sexo del cliente, definido como un Enum. Obligatorio.
    // EN: Client gender, defined as an Enum. Required field.
    @Column(nullable = false, length = 10)
    private Sexo sexo;

    // ES: Ciudad de residencia del cliente. Obligatoria.
    // EN: Client's city of residence. Required.
    @Column(nullable = false, length = 50)
    private String ciudad;

    // ES: Fecha de nacimiento del cliente. Se almacena como texto (DD/MM/AAAA). Obligatoria.
    // EN: Client's birth date stored as text (DD/MM/YYYY). Required.
    @Column(nullable = false, length = 10)
    private String fecha;

    // ES: Número telefónico del cliente. Obligatorio, longitud máxima 13 caracteres.
    // EN: Client's phone number. Required, max length 13 characters.
    @Column(nullable = false, length = 13)
    private String telefono;

    // ES: Correo electrónico del cliente. Obligatorio.
    // EN: Client's email address. Required.
    @Column(nullable = false, length = 50)
    private String correo;

    // ES: Constructor vacío requerido por JPA.
    // EN: Empty constructor required by JPA.
    public Cliente() {}

    // ES: Constructor que inicializa todos los campos excepto el ID.
    // EN: Constructor that initializes all fields except the autogenerated ID.
    public Cliente(String nombre, String apellidos, Sexo sexo, String ciudad, String fecha, String telefono, String correo) {
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.sexo = sexo;
        this.ciudad = ciudad;
        this.fecha = fecha;
        this.telefono = telefono;
        this.correo = correo;
    }

    // === Getters y Setters === //
    // ES: Métodos de acceso y modificación para cada campo.
    // EN: Accessor and mutator methods for each field.

    public long getId() {
        return id;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellidos() {
        return apellidos;
    }

    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    public Sexo getSexo() {
        return sexo;
    }

    public void setSexo(Sexo sexo) {
        this.sexo = sexo;
    }

    public String getCiudad() {
        return ciudad;
    }

    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }

    public String getFecha() {
        return fecha;
    }

    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

    public String getTelefono() {
        return telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public String getCorreo() {
        return correo;
    }

    public void setCorreo(String correo) {
        this.correo = correo;
    }

    // ES: Representación legible del cliente, útil para depuración o impresión en consola.
    // EN: Human-readable representation of the client, useful for debugging or console display.
    @Override
    public String toString() {
        return "Cliente: [" +
                "id=" + id +
                ", nombre='" + nombre + '\'' +
                ", apellidos='" + apellidos + '\'' +
                ", sexo='" + sexo + '\'' +
                ", ciudad='" + ciudad + '\'' +
                ", fecha='" + fecha + '\'' +
                ", telefono='" + telefono + '\'' +
                ", correo='" + correo + '\'' +
                ']';
    }

    // ES: Enumeración para los valores aceptados del sexo.
    // EN: Enumeration for accepted gender values.
    public enum Sexo {
        MASCULINO,
        FEMENINO
    }
}